% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={solution\_1},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{solution\_1}
\author{}
\date{\vspace{-2.5em}2024-09-02}

\begin{document}
\maketitle

\hypertarget{part-1-explanatory-analysis-of-the-dataset}{%
\subsection{Part 1: Explanatory analysis of the
dataset}\label{part-1-explanatory-analysis-of-the-dataset}}

\hypertarget{assumptions}{%
\subsubsection{Assumptions:}\label{assumptions}}

\begin{itemize}
\tightlist
\item
  linearity of covariate effects
\item
  homescedasticity of error variance --\textgreater{} error variacnce
  same for different dependent variables
\item
  uncorrelated error
\item
  additivity of errors
\end{itemize}

\hypertarget{diagnostics-plots}{%
\subsubsection{Diagnostics plots:}\label{diagnostics-plots}}

\begin{verbatim}
## Loading required package: carData
\end{verbatim}

\begin{verbatim}
## Loading required package: ggplot2
\end{verbatim}

\begin{verbatim}
## Registered S3 method overwritten by 'GGally':
##   method from   
##   +.gg   ggplot2
\end{verbatim}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{solution1_files/figure-latex/cars-1.pdf} \#\#\#
Relations: - medium strong (Cohen) , positive correlation between
education and wages and age and wages --\textgreater{} good if we want
to predict wages, bad if not, because then it shows multicollinearity -
weak (Cohen), negative correlation between age and education
--\textgreater{} again good for prediction of one of them, but bad if
not - there seems to be a small difference in wages between the sexes
(males gaining more than females) - no difference in wages regarding the
language level - about same distribution of education and age regarding
sex

\hypertarget{part-2-linear-regression-with-the-mylm-package}{%
\subsection{Part 2: Linear regression with the mylm
package}\label{part-2-linear-regression-with-the-mylm-package}}

\hypertarget{questions}{%
\subsubsection{Questions:}\label{questions}}

What is the interpretation of the parameter estimates? - The parameter
estimation shows the influence or strength of influence of the covariate
on the dependent variable. - The z- and p-values show if this effect in
the linear regression is significant or not, so if it would show as
well, if we would repeat the experiment. - The intercept shows the value
of the dependent varaible if all covariatees are 0.

\begin{verbatim}
## 
## Attaching package: 'mylm'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:carData':
## 
##     SLID
\end{verbatim}

\begin{verbatim}
## Call:
## mylm(formula = wages ~ education, data = SLID)
## 
## Coefficients:
## (Intercept) : 4.9717 
## education : 0.7923
\end{verbatim}

\begin{verbatim}
## Call:
## mylm(formula = wages ~ education, data = SLID)
## 
## Residuals:
## Min       1Q        Median    3Q        Max       
## -17.688   -5.822    -1.039    4.148     34.190    
## 
## Coefficients:
##               Estimate     Std. Error   z value      Pr(>|z|)     
## (Intercept)   4.971691     0.5344       9.3040       0.0000 ***   
## education     0.7923091    0.0391       20.2816      0.0000 ***   
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  7.493 on  3984 degrees of freedom 
## Multiple R-squared:  0.09359 ,  Adjusted R-squared:  0.09313 
## F-statistic:  411.3 on 1 and 3984 DF, p-value: 0.000
\end{verbatim}

\begin{verbatim}
## 
## Call:
## lm(formula = wages ~ education, data = SLID)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.688  -5.822  -1.039   4.148  34.190 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(>|t|)    
## (Intercept)  4.97169    0.53429   9.305   <2e-16 ***
## education    0.79231    0.03906  20.284   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 7.492 on 3985 degrees of freedom
## Multiple R-squared:  0.09359,    Adjusted R-squared:  0.09336 
## F-statistic: 411.4 on 1 and 3985 DF,  p-value: < 2.2e-16
\end{verbatim}

\hypertarget{plot}{%
\subsubsection{Plot}\label{plot}}

\includegraphics{solution1_files/figure-latex/linear regression plot-1.pdf}

\hypertarget{comments}{%
\subsubsection{Comments:}\label{comments}}

\begin{itemize}
\tightlist
\item
  Heteroscadicity, so for larger fitted values the prediction gets less
  precise and the errors are more widely spread --\textgreater{} This
  indicates that there might be an error in the way the covariates are
  modelled.
\item
  We have only little data for the higher values of wages, so this might
  make the prediction harder as there is less to fit/ learn from.
\item
  Also, the distribution for the positive residuals has a higher
  variance than for the negative one.
\end{itemize}

\hypertarget{anova}{%
\subsubsection{ANOVA}\label{anova}}

-What is the residual sum of squares (SSE) and the degrees of freedom
for this model? See output. -What is total sum of squares (SST) for this
model? Test the significance of the regression using a 𝜒2-test. 23096
(Sum Sq education) + 223694 (sum sq residuals) = 246790. -What is the
relationship between the 𝜒2- and 𝑧-statistic in simple linear
regression? Find the critical value(s) for both tests. As there is only
one beta to test in simple linear regression the chi\^{}2 for the whole
model should be the squared z statistic for education, which is true for
our values Chi\^{}2 = 411 and z = 20.284 (20.284\^{}2 = 411.44).

\begin{verbatim}
## [1] "wages~"
## Analysis of Variance Table
## Response: wages
##               Df         Sum Sq     Mean Sq    Chi^2      Pr(>Chi^2) 
## education     1          23096      23096      411.447    0 ***      
## Residuals     3984       223694     56        
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Total Sum SQ: 246790 
## Chi-statistic:  411.3 on 3984 DF, p-value: 0.000
\end{verbatim}

\hypertarget{comments-1}{%
\subsubsection{Comments:}\label{comments-1}}

\begin{itemize}
\tightlist
\item
  The covariate education gets a significant chi\^{}2 value which means
  there is a high probability that it explains variance of the dependent
  variable.
\end{itemize}

\hypertarget{part-3-multiple-linear-regression}{%
\section{Part 3: Multiple Linear
Regression}\label{part-3-multiple-linear-regression}}

-What are the estimates and standard errors of the intercepts and
regression coefficients for this model? -Test the significance of the
coefficients using a 𝑧-test. -What is the interpretation of the
parameters?

\begin{verbatim}
## Call:
## mylm(formula = wages ~ education + age, data = SLID)
## 
## Residuals:
## Min       1Q        Median    3Q        Max       
## -24.303   -4.495    -0.807    3.674     37.628    
## 
## Coefficients:
##               Estimate     Std. Error   z value      Pr(>|z|)     
## (Intercept)   -6.021653    0.6190       -9.7280      0.0000 ***   
## education     0.9014644    0.0358       25.2057      0.0000 ***   
## age           0.2570898    0.0090       28.7176      0.0000 ***   
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  6.821 on  3983 degrees of freedom 
## Multiple R-squared:  0.2491 ,  Adjusted R-squared:  0.2485 
## F-statistic:  660.5 on 2 and 3983 DF, p-value: 0.000
\end{verbatim}

What is the interpretation of the parameters? - The intercept is
negative, probably because all data points (persons) have an age higher
than 0. - Education seems to have a higher influence than age as the
parameter estimate is higher. - Both parameters are significant, so
should have an influence on wages.

\hypertarget{comparison-simple-linear-regression-and-multiple-linear-regression}{%
\subsubsection{Comparison simple linear regression and multiple linear
regression}\label{comparison-simple-linear-regression-and-multiple-linear-regression}}

\begin{verbatim}
## Call:
## mylm(formula = wages ~ education, data = SLID)
## 
## Residuals:
## Min       1Q        Median    3Q        Max       
## -17.688   -5.822    -1.039    4.148     34.190    
## 
## Coefficients:
##               Estimate     Std. Error   z value      Pr(>|z|)     
## (Intercept)   4.971691     0.5344       9.3040       0.0000 ***   
## education     0.7923091    0.0391       20.2816      0.0000 ***   
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  7.493 on  3984 degrees of freedom 
## Multiple R-squared:  0.09359 ,  Adjusted R-squared:  0.09313 
## F-statistic:  411.3 on 1 and 3984 DF, p-value: 0.000
\end{verbatim}

\begin{verbatim}
## Call:
## mylm(formula = wages ~ age, data = SLID)
## 
## Residuals:
## Min       1Q        Median    3Q        Max       
## -17.747   -4.847    -1.507    3.914     35.063    
## 
## Coefficients:
##               Estimate     Std. Error   z value      Pr(>|z|)     
## (Intercept)   6.890901     0.3741       18.4202      0.0000 ***   
## age           0.2331079    0.0096       24.3222      0.0000 ***   
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  7.344 on  3984 degrees of freedom 
## Multiple R-squared:  0.1293 ,  Adjusted R-squared:  0.1289 
## F-statistic:  591.6 on 1 and 3984 DF, p-value: 0.000
\end{verbatim}

\begin{verbatim}
## Call:
## mylm(formula = wages ~ education + age, data = SLID)
## 
## Residuals:
## Min       1Q        Median    3Q        Max       
## -24.303   -4.495    -0.807    3.674     37.628    
## 
## Coefficients:
##               Estimate     Std. Error   z value      Pr(>|z|)     
## (Intercept)   -6.021653    0.6190       -9.7280      0.0000 ***   
## education     0.9014644    0.0358       25.2057      0.0000 ***   
## age           0.2570898    0.0090       28.7176      0.0000 ***   
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  6.821 on  3983 degrees of freedom 
## Multiple R-squared:  0.2491 ,  Adjusted R-squared:  0.2485 
## F-statistic:  660.5 on 2 and 3983 DF, p-value: 0.000
\end{verbatim}

\begin{verbatim}
## Call:
## mylm(formula = age ~ education, data = SLID)
## 
## Residuals:
## Min        1Q         Median     3Q         Max        
## -25.9116   -8.9982    -0.6658    8.9097     33.8817    
## 
## Coefficients:
##               Estimate      Std. Error    z value       Pr(>|z|)      
## (Intercept)   42.76072      0.8609        49.6726       0.0000 ***    
## education     -0.4245804    0.0629        -6.7464       2e-11 ***     
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  12.07 on  3984 degrees of freedom 
## Multiple R-squared:  0.0113 ,  Adjusted R-squared:  0.0108 
## F-statistic:  45.5 on 1 and 3984 DF, p-value: 2e-11
\end{verbatim}

Why (and when) does the parameter estimates found (the two simple and
the one multiple) differ? - They should not differ, if the covariates so
age and education are independent (no correlation). - They differ
because age and education are correlated. Explain/show how you can use
mylm to find these values. --\textgreater{} Use the function on the
model.

\hypertarget{part-4-testing-mylm}{%
\section{Part 4: Testing mylm}\label{part-4-testing-mylm}}

\begin{verbatim}
## Call:
## mylm(formula = wages ~ sex + age + language + I(education^2), 
##     data = SLID)
## 
## Residuals:
## Min        1Q         Median     3Q         Max        
## -27.1712   -4.2762    -0.7631    3.2176     35.9289    
## 
## Coefficients:
##                  Estimate       Std. Error     z value        Pr(>|z|)       
## (Intercept)      -1.875531      0.4404         -4.2587        2e-05 ***      
## sexMale          3.4087         0.2084         16.3529        0.0000 ***     
## age              0.248625       0.0087         28.6973        0.0000 ***     
## languageFrench   -0.07553202    0.4252         -0.1776        0.8590         
## languageOther    -0.1345402     0.3232         -0.4163        0.6772         
## I(education^2)   0.03481515     0.0013         26.9873        0.0000 ***     
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  6.578 on  3980 degrees of freedom 
## Multiple R-squared:  0.3022 ,  Adjusted R-squared:  0.3012 
## F-statistic:  344.8 on 5 and 3980 DF, p-value: 0.000
\end{verbatim}

\includegraphics{solution1_files/figure-latex/Test mylm 1-1.pdf}

That sex/ gender has a significant influence on the wages as well as
age. Language has no significant effect and the squared education has an
effect but a really small one. The model explains about 30\% of the
variance. We could leave out the language because it is unnecessary.

\begin{verbatim}
## Call:
## mylm(formula = wages ~ language + age + language * age, data = SLID)
## 
## Residuals:
## Min       1Q        Median    3Q        Max       
## -16.751   -4.832    -1.412    3.938     35.187    
## 
## Coefficients:
##                      Estimate       Std. Error     z value        Pr(>|z|)       
## (Intercept)          6.555794       0.4107         15.9612        0.0000 ***     
## languageFrench       2.860625       1.5963         1.7921         0.0731 .       
## languageOther        0.8486213      1.2353         0.6870         0.4921         
## age                  0.2448516      0.0107         22.9072        0.0000 ***     
## languageFrench:age   -0.08392752    0.0405         -2.0743        0.0381 *       
## languageOther:age    -0.03701381    0.0293         -1.2614        0.2072         
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  7.34 on  3980 degrees of freedom 
## Multiple R-squared:  0.1312 ,  Adjusted R-squared:  0.1299 
## F-statistic:  120.2 on 5 and 3980 DF, p-value: 0.000
\end{verbatim}

\includegraphics{solution1_files/figure-latex/Test mylm 2-1.pdf}

Language is still insignificant, age has an effect on wages. Also the
interaction of languageFrench and age is significant. But the
interaction term has only a small estimate. The model explains about
13\% of the variance. In this model, I probably would add sex again,
because it seems to explain a large proportion of variance.

\begin{verbatim}
## Call:
## mylm(formula = wages ~ education - 1, data = SLID)
## 
## Residuals:
## Min        1Q         Median     3Q         Max        
## -19.8039   -5.3421    -0.6624    4.4646     36.3264    
## 
## Coefficients:
##             Estimate    Std. Error  z value     Pr(>|z|)    
## education   1.146697    0.0088      130.7776    0.0000 ***
\end{verbatim}

\begin{verbatim}
## Warning in pf(F_stat, df1 = object$rank - 1, df2 = object$dof_residuals): NaNs
## produced
\end{verbatim}

\begin{verbatim}
## 
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## Residual standard error:  7.573 on  3985 degrees of freedom 
## Multiple R-squared:  0.07389 ,  Adjusted R-squared:  0.07366 
## F-statistic:  Inf on 0 and 3985 DF, p-value: NaN
\end{verbatim}

\includegraphics{solution1_files/figure-latex/Test mylm 3x-1.pdf}

As there is no intercept the for a education of zero there is also a
wage of zero now. The parameter for education is greater than with the
intercept, as it has to compensate for the missing intercept. Also, the
R\^{}2 is smaller. We would recommend adding the intercept.

\end{document}
